/* See LICENSE file for copyright and license details. */

#ifndef LIBFE310_PERIPH_HW_PRCI_H
#define LIBFE310_PERIPH_HW_PRCI_H

#include <fe310/bits.h>

#define PRCI_BASE 0x10008000

#define PRCI_HFROSCCFG_DIV GENMASK(5, 0)
#define PRCI_HFROSCCFG_TRIM GENMASK(20, 16)
#define PRCI_HFROSCCFG_EN BITMASK(30)
#define PRCI_HFROSCCFG_RDY BITMASK(31)
#define PRCI_HFXOSCCFG_EN BITMASK(30)
#define PRCI_HFXOSCCFG_RDY BITMASK(31)
#define PRCI_PLLCFG_R GENMASK(2, 0)
#define PRCI_PLLCFG_F GENMASK(9, 4)
#define PRCI_PLLCFG_Q GENMASK(11, 10)
#define PRCI_PLLCFG_SEL BITMASK(16)
#define PRCI_PLLCFG_REFSEL BITMASK(17)
#define PRCI_PLLCFG_BYPASS BITMASK(18)
#define PRCI_PLLCFG_LOCK BITMASK(31)
#define PRCI_PLLOUTDIV_DIV GENMASK(5, 0)
#define PRCI_PLLOUTDIV_BY1 BITMASK(8)
#define PRCI_PROCMONCFG_DIVSEL GENMASK(4, 0)
#define PRCI_PROCMONCFG_DELAYSEL GENMASK(12, 8)
#define PRCI_PROCMONCFG_EN BITMASK(16)
#define PRCI_PROCMONCFG_SEL GENMASK(25, 24)

#endif /* LIBFE310_PERIPH_HW_PRCI_H */
