/* See LICENSE file for copyright and license details. */

#ifndef LIBFE310_PERIPH_HW_SPI_H
#define LIBFE310_PERIPH_HW_SPI_H

#include <fe310/bits.h>

#define SPI0_BASE 0x10014000
#define SPI1_BASE 0x10024000
#define SPI2_BASE 0x10034000

#define SPI_SCKDIV_DIV GENMASK(11, 0)
#define SPI_SCKMODE_PHA BITMASK(0)
#define SPI_SCKMODE_POL BITMASK(1)
/* #define SPI_CSID */
/* #define SPI_CSDEF */
#define SPI_CSMODE_MODE GENMASK(1, 0)
#define SPI_DELAY0_CSSCK GENMASK(7, 0)
#define SPI_DELAY0_SCKCS GENMASK(23, 16)
#define SPI_DELAY1_INTERCS GENMASK(7, 0)
#define SPI_DELAY1_INTERXFR GENMASK(23, 16)
#define SPI_FMT_PROTO GENMASK(1, 0)
#define SPI_FMT_ENDIAN BITMASK(2)
#define SPI_FMT_DIR BITMASK(3)
#define SPI_FMT_LEN GENMASK(19, 16)
#define SPI_TXDATA_DATA GENMASK(7, 0)
#define SPI_TXDATA_FULL BITMASK(31)
#define SPI_RXDATA_DATA GENMASK(7, 0)
#define SPI_RXDATA_EMPTY BITMASK(31)
#define SPI_TXMARK_TXMARK GENMASK(2, 0)
#define SPI_RXMARK_RXMARK GENMASK(2, 0)
#define SPI_IE_TXWM BITMASK(0)
#define SPI_IE_RXWM BITMASK(1)
#define SPI_IP_TXWM BITMASK(0)
#define SPI_IP_RXWM BITMASK(1)
#define SPI_FCTRL_EN BITMASK(0)
#define SPI_FFMT_CMD_EN BITMASK(0)
#define SPI_FFMT_ADDR_LEN GENMASK(3, 1)
#define SPI_FFMT_PAD_CNT GENMASK(7, 4)
#define SPI_FFMT_CMD_PROTO GENMASK(9, 8)
#define SPI_FFMT_ADDR_PROTO GENMASK(11, 10)
#define SPI_FFMT_DATA_PROTO GENMASK(13, 12)
#define SPI_FFMT_CMD_CODE GENMASK(23, 16)
#define SPI_FFMT_PAD_CODE GENMASK(31, 24)

#define SPI_FMT_LEN_MAX 8

#define GPIO_SPI1_CS0 BITMASK(2)
#define GPIO_SPI1_DQ0 BITMASK(3)
#define GPIO_SPI1_DQ1 BITMASK(4)
#define GPIO_SPI1_SCK BITMASK(5)
#define GPIO_SPI1_DQ2 BITMASK(6)
#define GPIO_SPI1_DQ3 BITMASK(7)
#define GPIO_SPI1_CS1 BITMASK(8)
#define GPIO_SPI1_CS2 BITMASK(9)
#define GPIO_SPI1_CS3 BITMASK(10)
#define GPIO_SPI2_CS0 BITMASK(26)
#define GPIO_SPI2_DQ0 BITMASK(27)
#define GPIO_SPI2_DQ1 BITMASK(28)
#define GPIO_SPI2_SCK BITMASK(29)
#define GPIO_SPI2_DQ2 BITMASK(30)
#define GPIO_SPI2_DQ3 BITMASK(31)

#endif /* LIBFE310_PERIPH_HW_SPI_H */
